// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "rapidfdmlcm_airstate.h"

static int __rapidfdmlcm_airstate_hash_computed;
static uint64_t __rapidfdmlcm_airstate_hash;

uint64_t __rapidfdmlcm_airstate_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __rapidfdmlcm_airstate_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__rapidfdmlcm_airstate_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x334a3d64a11de7d9LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __rapidfdmlcm_airstate_get_hash(void)
{
    if (!__rapidfdmlcm_airstate_hash_computed) {
        __rapidfdmlcm_airstate_hash = (int64_t)__rapidfdmlcm_airstate_hash_recursive(NULL);
        __rapidfdmlcm_airstate_hash_computed = 1;
    }

    return __rapidfdmlcm_airstate_hash;
}

int __rapidfdmlcm_airstate_encode_array(void *buf, int offset, int maxlen, const rapidfdmlcm_airstate *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].rho), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].wind_speed, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int rapidfdmlcm_airstate_encode(void *buf, int offset, int maxlen, const rapidfdmlcm_airstate *p)
{
    int pos = 0, thislen;
    int64_t hash = __rapidfdmlcm_airstate_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __rapidfdmlcm_airstate_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __rapidfdmlcm_airstate_encoded_array_size(const rapidfdmlcm_airstate *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(&(p[element].rho), 1);

        size += __float_encoded_array_size(p[element].wind_speed, 3);

    }
    return size;
}

int rapidfdmlcm_airstate_encoded_size(const rapidfdmlcm_airstate *p)
{
    return 8 + __rapidfdmlcm_airstate_encoded_array_size(p, 1);
}

int __rapidfdmlcm_airstate_decode_array(const void *buf, int offset, int maxlen, rapidfdmlcm_airstate *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].rho), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].wind_speed, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __rapidfdmlcm_airstate_decode_array_cleanup(rapidfdmlcm_airstate *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(&(p[element].rho), 1);

        __float_decode_array_cleanup(p[element].wind_speed, 3);

    }
    return 0;
}

int rapidfdmlcm_airstate_decode(const void *buf, int offset, int maxlen, rapidfdmlcm_airstate *p)
{
    int pos = 0, thislen;
    int64_t hash = __rapidfdmlcm_airstate_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __rapidfdmlcm_airstate_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int rapidfdmlcm_airstate_decode_cleanup(rapidfdmlcm_airstate *p)
{
    return __rapidfdmlcm_airstate_decode_array_cleanup(p, 1);
}

int __rapidfdmlcm_airstate_clone_array(const rapidfdmlcm_airstate *p, rapidfdmlcm_airstate *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(&(p[element].rho), &(q[element].rho), 1);

        __float_clone_array(p[element].wind_speed, q[element].wind_speed, 3);

    }
    return 0;
}

rapidfdmlcm_airstate *rapidfdmlcm_airstate_copy(const rapidfdmlcm_airstate *p)
{
    rapidfdmlcm_airstate *q = (rapidfdmlcm_airstate*) malloc(sizeof(rapidfdmlcm_airstate));
    __rapidfdmlcm_airstate_clone_array(p, q, 1);
    return q;
}

void rapidfdmlcm_airstate_destroy(rapidfdmlcm_airstate *p)
{
    __rapidfdmlcm_airstate_decode_array_cleanup(p, 1);
    free(p);
}

int rapidfdmlcm_airstate_publish(lcm_t *lc, const char *channel, const rapidfdmlcm_airstate *p)
{
      int max_data_size = rapidfdmlcm_airstate_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = rapidfdmlcm_airstate_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _rapidfdmlcm_airstate_subscription_t {
    rapidfdmlcm_airstate_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void rapidfdmlcm_airstate_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    rapidfdmlcm_airstate p;
    memset(&p, 0, sizeof(rapidfdmlcm_airstate));
    status = rapidfdmlcm_airstate_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding rapidfdmlcm_airstate!!!\n", status);
        return;
    }

    rapidfdmlcm_airstate_subscription_t *h = (rapidfdmlcm_airstate_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    rapidfdmlcm_airstate_decode_cleanup (&p);
}

rapidfdmlcm_airstate_subscription_t* rapidfdmlcm_airstate_subscribe (lcm_t *lcm,
                    const char *channel,
                    rapidfdmlcm_airstate_handler_t f, void *userdata)
{
    rapidfdmlcm_airstate_subscription_t *n = (rapidfdmlcm_airstate_subscription_t*)
                       malloc(sizeof(rapidfdmlcm_airstate_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 rapidfdmlcm_airstate_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg rapidfdmlcm_airstate LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int rapidfdmlcm_airstate_subscription_set_queue_capacity (rapidfdmlcm_airstate_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int rapidfdmlcm_airstate_unsubscribe(lcm_t *lcm, rapidfdmlcm_airstate_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe rapidfdmlcm_airstate_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

