function obj = init_attitude_controller(fixed_step_ode,ode_steps)
obj = struct('RollCtrl',init_adaptive_controller(fixed_step_ode,ode_steps),...
    'PitchCtrl',init_adaptive_controller(fixed_step_ode,ode_steps),...
    'YawCtrl',init_adaptive_controller(fixed_step_ode,ode_steps),...
    'quat_sp',[1 0 0 0],'quat',[1 0 0 0],'u',[0 0 0],'debug_time_used',0);
coder.cstructname(obj,'AttitudeCtrlT')
end