function ctrl = init_adaptive_controller(fixed_step_ode,ode_steps)
filter_obj = make_iter_trans(2);
ctrl = struct('t',0,'x',[0; 0; 1.0; 0.0; 0.0; 0 ; 0],'Gamma',0,...
'P',[0 0; 0 0],'Am',[0 0;0 0],'u',0,'b',[0;0],'kg',0,'kg_rate',0,...
'u_filter',filter_obj,'g_filter',filter_obj,'inited',false,'err',[0;0],...
'eta',0,'r',0,'rdot',0,'g',[0;0],'g_by_x',[0 0;0 0],'km',[0;0],'x_real',[0;0],...
'fixed_step_ode',fixed_step_ode,'ode_steps',ode_steps,'out',0,...
'actuator_estimator',InitActuatorEstimator(),'p_actuator',1);
%coder.cstructname(ctrl, 'AdaptiveCtrlT');
%coder.cstructname(ctrl.actuator_estimator,'ActuatorEstimatior');
end